# common definitions for APIs which will be created by the scenario
api:
  throttling_tier: Unlimited
  visibility: PUBLIC
  production_endpoint: https://localhost:9443/am/sample/pizzashack/v1/api/
  sandbox_endpoint: https://localhost:9443/am/sample/pizzashack/v1/api/

# common definitions for applications which will be created by the scenario
application:
  throttling_tier: Unlimited
  token_validity_period: -1

# subscription tier to be used when subscribing APIs
subscription_tier: Unlimited

# details for all hosted APIs. Traffic tool will invoke according to these configurations
api_host:
  protocol: https
  ip: localhost
  port: 8243

# configurations for the traffic tool processes
tool_config:
  no_of_users: 100
  max_connection_refuse_count: 50
  no_of_data_points: 100000
  heavy_traffic: false
  start_timestamp: 2020-12-03T20:56:35.450686Z    # ISO 8601 format
  frequency_limits:
    low:
      lower: 0
      upper: 10
    medium:
      lower: 10
      upper: 30
    high:
      lower: 30
      upper: 60

# payloads to send with POST and DELETE requests
payloads:
  post:
    - {"customerName": "customer_1","delivered": true,"address": "customer1_address","pizzaType": "customer_pizza","creditCardNumber": "customer_credit_card","quantity": 0,"orderId": "1"}
    - {"customerName": "customer_2","delivered": true,"address": "customer2_address","pizzaType": "customer_pizza","creditCardNumber": "customer_credit_card","quantity": 4,"orderId": "2"}
    - {"customerName": "customer_3","delivered": true,"address": "customer3_address","pizzaType": "customer_pizza","creditCardNumber": "customer_credit_card","quantity": 1,"orderId": "3"}

  delete:


# Traffic tool will randomly append one of the following user agents to the request header
user_agents:
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
  - Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
  - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
  - Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:24.0) Gecko/20100101 Firefox/24.0
  - Opera/9.80 (Linux armv7l) Presto/2.12.407 Version/12.51 , D50u-D1-UHD/V1.5.16-UHD (Vizio, D50u-D1, Wireless)
  - Mozilla/5.0 (iPhone; CPU iPhone OS 12_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko)
  - Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
